
return {
	ante_up                 = {order = 1,  tier = 3, earned = false, steamid = "BAL_01"},
	ante_upper              = {order = 2,  tier = 3, earned = false, steamid = "BAL_02"},
	heads_up                = {order = 3,  tier = 2, earned = false, steamid = "BAL_03"},
	low_stakes              = {order = 4,  tier = 2, earned = false, steamid = "BAL_04"},
	mid_stakes              = {order = 5,  tier = 2, earned = false, steamid = "BAL_05"},
	high_stakes             = {order = 6,  tier = 2, earned = false, steamid = "BAL_06"},
	card_player             = {order = 7,  tier = 3, earned = false, steamid = "BAL_07"},
	card_discarder          = {order = 8,  tier = 3, earned = false, steamid = "BAL_08"},
	nest_egg                = {order = 9,  tier = 2, earned = false, steamid = "BAL_09"},
	flushed                 = {order = 10, tier = 3, earned = false, steamid = "BAL_10"},
	speedrunner             = {order = 11, tier = 2, earned = false, steamid = "BAL_11"},
	roi                     = {order = 12, tier = 3, earned = false, steamid = "BAL_12"},
	shattered               = {order = 13, tier = 3, earned = false, steamid = "BAL_13"},
	royale                  = {order = 14, tier = 3, earned = false, steamid = "BAL_14"},
	retrograde              = {order = 15, tier = 2, earned = false, steamid = "BAL_15"},
	_10k                    = {order = 16, tier = 3, earned = false, steamid = "BAL_16"},
	_1000k                  = {order = 17, tier = 2, earned = false, steamid = "BAL_17"},
	_100000k                = {order = 18, tier = 1, earned = false, steamid = "BAL_18"},
	tiny_hands              = {order = 19, tier = 2, earned = false, steamid = "BAL_19"},
	big_hands               = {order = 20, tier = 2, earned = false, steamid = "BAL_20"},
	you_get_what_you_get    = {order = 21, tier = 3, earned = false, steamid = "BAL_21"},
	rule_bender             = {order = 22, tier = 3, earned = false, steamid = "BAL_22"},
	rule_breaker            = {order = 23, tier = 1, earned = false, steamid = "BAL_23"},
	legendary               = {order = 24, tier = 3, earned = false, steamid = "BAL_24"},
	astronomy               = {order = 25, tier = 3, earned = false, steamid = "BAL_25"},
	cartomancy              = {order = 26, tier = 3, earned = false, steamid = "BAL_26"},
	clairvoyance            = {order = 27, tier = 2, earned = false, steamid = "BAL_27"},
	extreme_couponer        = {order = 28, tier = 1, earned = false, steamid = "BAL_28"},
	completionist           = {order = 29, tier = 1, earned = false, steamid = "BAL_29"},
	completionist_plus      = {order = 30, tier = 1, earned = false, steamid = "BAL_30"},
	completionist_plus_plus = {order = 31, tier = 1, earned = false, steamid = "BAL_31"},
}
