return {
    "button",
    "button_UI",
    "one_press",
    "hook_fn",
    "hover_hook_fn",
    "hover_jitter",
    "slot_idx",
    "save_slot_id",
    "save_slot_meta",
    "primary_on_empty",
    "secondary_action",
    "secondary_hook_fn",
    "hid_action",
    "hid_button",
}
